Update to use gmtoolkit
This helps to reduce the overall RAM usage improving stability

diff --git a/ports/jetlancer/jetlancer/tools/patchscript b/ports/jetlancer/jetlancer/tools/patchscript
--- a/ports/jetlancer/jetlancer/tools/patchscript
+++ b/ports/jetlancer/jetlancer/tools/patchscript
@@ -2,33 +2,93 @@
 # Set GAMEDIR to the current directory and set logfile
 GAMEDIR="$PWD"
 LOGFILE="$GAMEDIR/patchlog.txt"
+LOGERR="$GAMEDIR/patchlog_error.txt"
+START_TIME=$(date +%s)
 
 # Redirect output and error to the log file
 exec > >(tee -a "$LOGFILE") 2>&1
 echo "GAMEDIR is set to: $GAMEDIR"
 
+# Patch failure function
+patch_failure() {
+    mv "$LOGFILE" "$LOGERR"
+    $ESUDO umount "$DOTNETDIR"
+    $ESUDO umount "$TOOLKIT"
+    echo "Patching process failed."
+    exit 1
+}
+
+# Mount the GMToolkit runtime
+TOOLKIT="$HOME/gmtoolkit"
+RUNTIME="$controlfolder/libs/gmtoolkit.squashfs"
+if [ -f "$RUNTIME" ]; then
+    $ESUDO mkdir -p "$TOOLKIT"
+    $ESUDO umount "$RUNTIME" || true
+    $ESUDO mount "$RUNTIME" "$TOOLKIT"
+else
+    echo "This port requires the GMToolkit runtime. Please download it."
+    sleep 2
+    patch_failure
+fi
+
+# Mount the dotnet runtime
+DOTNETDIR="$HOME/mono"
+DOTNETFILE="$controlfolder/libs/dotnet-8.0.12.squashfs"
+if [ -f "$DOTNETFILE" ]; then
+    $ESUDO mkdir -p "$DOTNETDIR"
+    $ESUDO umount "$DOTNETFILE" || true
+    $ESUDO mount "$DOTNETFILE" "$DOTNETDIR"
+else
+    echo "This port requires the Dotnet runtime. Please download it."
+    sleep 2
+    patch_failure
+fi
+
 # Exports
+export PATH="$controlfolder:$DOTNETDIR:$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
+export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"
+export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
 export DATADIR="$GAMEDIR/assets"
 export DATAFILE="game.port"
-export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/lib:$GAMEDIR/tools/libs:$LD_LIBRARY_PATH"
-export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
-export TOOLDIR="$GAMEDIR/tools"
 export TMPDIR="$GAMEDIR/tmp"
-export PATH="$controlfolder:$GAMEDIR/tools:$PATH"
 
 # Permissions
 chmod 666 /dev/uinput
-chmod 777 "$TOOLDIR/gmKtool.py"
-chmod 777 "$TOOLDIR/oggenc"
-chmod 777 "$TOOLDIR/oggdec"
+chmod 777 "$TOOLKIT/gmtools/gmKtool.py"
+chmod 777 "$TOOLKIT/gmtools/oggdec"
+chmod 777 "$TOOLKIT/gmtools/oggdec"
 
-cd "$GAMEDIR"
+# Set up trap for cleaning TMPDIR on exit
+trap 'rm -rf "$TMPDIR"; echo "Cleaned up temporary files." >> "$LOGFILE"' 0
 
-remove_files() {
-    # Delete unnecessary files
-    rm -rf $DATADIR/*.exe $DATADIR/*.dll $DATADIR/.gitkeep
-	echo "Removed unnecessary files"
-    sleep 1
+# Attempt to get SAVEDIR from gmloader.json using jq
+if command -v jq >/dev/null 2>&1; then
+    SAVEDIR=$(jq -r '.save_dir // empty' "$GAMEDIR/gmloader.json" 2>/dev/null)
+else
+    SAVEDIR="$GAMEDIR/saves"
+fi
+
+# Test for commands: python, zip
+PYTHON=$(which python3)
+if [ -z "$PYTHON" ]; then
+    echo "Missing Python!"
+    patch_failure
+fi
+
+ZIP=$(which zip)
+if [ -z "$ZIP" ]; then
+    echo "Missing zip!"
+    patch_failure
+fi
+
+prepare_files() {
+	# Create the savedir
+	mkdir -p $SAVEDIR
+	
+	# Delete files we don't need
+	rm -rf "$DATADIR"/*.exe "$DATADIR"/*.dll "$DATADIR"/*.ico "$DATADIR"/.gitkeep
+	
+	sleep 1
 }
 
 apply_xdeltas() {
@@ -39,12 +99,11 @@ apply_xdeltas() {
     
         # Checksum for the GOG version
         if [ "$checksum" = "0258cadce342712c2ffbd5fc70e0dfd7" ]; then
-            $ESUDO xdelta3 -d -s $DATADIR/data.win -f $TOOLDIR/patch/gogdata.xdelta $DATADIR/game.droid && \
-            rm $DATADIR/data.win
-            echo "GOG data.win has been patched"
+            mv $DATADIR/data.win $DATADIR/data2.win
+            echo "GOG data.win has been renamed to data2.win"
         # Checksum for the Steam version
         elif [ "$checksum" = "86045b6464bb909851634c3e34b2a82e" ]; then
-            $ESUDO xdelta3 -d -s $DATADIR/data.win -f $TOOLDIR/patch/steamdata.xdelta $DATADIR/game.droid && \
+            $ESUDO xdelta3 -d -s $DATADIR/data.win -f tools/patch/steamdata.xdelta $DATADIR/data2.win && \
             rm $DATADIR/data.win
  	        echo "Steam data.win has been patched"
         else
@@ -61,7 +120,7 @@ apply_xdeltas() {
     
         # Checksum for the Steam audiogroup1.dat version
         if [ "$checksum" = "bcadc44e45f8a6caf9b5c5db538ced13" ]; then
-            $ESUDO xdelta3 -d -s $DATADIR/audiogroup1.dat -f $TOOLDIR/patch/steamaudiogroup1.xdelta $DATADIR/audiogroup1patched.dat && \
+            $ESUDO xdelta3 -d -s $DATADIR/audiogroup1.dat -f tools/patch/steamaudiogroup1.xdelta $DATADIR/audiogroup1patched.dat && \
             rm $DATADIR/audiogroup1.dat
             mv $DATADIR/audiogroup1patched.dat $DATADIR/audiogroup1.dat
             echo "Steam audiogroup1.dat has been patched."
@@ -71,32 +130,40 @@ apply_xdeltas() {
     fi
 }
 
-compress_audio() {
-    echo "Compressing audio..."
-    # Clear out the temporary directory
-    mkdir -p "$TMPDIR"
-    rm -rf $TMPDIR/*
+# Externalize game textures with compression
+dump_textures() {
+    # Purge cache before operations
+    rm -rf "$TMPDIR/"*
+    
+    # Begin texture operations
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
+        dump "$DATADIR/data2.win" \
+        -e "$DATADIR/textures" "$DATADIR/game.droid"
 
-    # Run the compression tool
-    echo "Running GMTools on data and audiogroups."
-    $PYTHON $TOOLDIR/gmKtool.py -vv -m 0 -r -q -1 -d "$TMPDIR" "$DATADIR/game.droid"
-
-    if [ $? -eq 0 ]; then
-        echo "Compression completed successfully."
-        mv "$TMPDIR/"* "$DATADIR"
-        echo "Moved compressed files to $DATADIR."
-        rm -rf "$TMPDIR"
-        echo "Temporary directory $TMPDIR removed."
-        echo "Audio compression applied successfully."
-        sleep 1
+    if [ $? -ne 0 ]; then
+        echo "[DOTNET]: Texture dumping failed to apply."
+        patch_failure
     else
-        echo "Audio compression failed."
-        echo "Cleaning up temporary directory $TMPDIR."
-        rm -rf "$TMPDIR"
-        sleep 1
+        rm -f "$DATADIR/data2.win"
+        mv "$DATADIR/textures" "$SAVEDIR/textures"
+        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
     fi
 	
-	sleep 3
+	sleep 1
+}
+
+compress_audio() {  
+    if $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"; then
+        mv "$TMPDIR/"* "$DATADIR" && rmdir "$TMPDIR"
+        echo "Audio compression applied successfully."
+    else
+        # Failure
+        echo "Audio compression failed for game.droid."
+        rmdir "$TMPDIR"
+        patch_failure
+    fi
+	
+	sleep 1
 	
 	# Find and compress all .ogg files in the /gamedata directory
     find "$DATADIR" -type f -name "*.ogg" | while read -r file; do
@@ -104,49 +171,62 @@ compress_audio() {
     temp_file="${file%.ogg}_temp.ogg"
 
     # Decode the .ogg file and encode it with the specified bitrate
-    "$TOOLDIR/oggdec" -o - "$file" | "$TOOLDIR/oggenc" -q -1 -o "$temp_file" -
+    "$TOOLKIT/gmtools/oggdec" -o - "$file" 2>/dev/null | "$TOOLKIT/gmtools/oggenc" -b 64 -o "$temp_file" - 2>/dev/null
     if [ $? -eq 0 ]; then
         # Replace the original file with the compressed version if successful
         mv "$temp_file" "$file"
-        echo "Compressed: $file to quality -1.00"
+        echo "Compressed: $file to 64 kbps"
     else
         echo "Failed to compress: $file" >&2
         rm -f "$temp_file" # Clean up the temp file in case of error
     fi
     done
-
-    echo "All .ogg files have been processed."
-    sleep 3 
 	
+    echo "All .ogg files have been processed."
+
+    sleep 1
 }
 
 zip_archive() {
-        zip -r -0 $DATAFILE ./assets/
-        rm -rf ./assets
-        mkdir -p saves
+        zip -r -0 "$DATAFILE" ./assets/
+        echo "Zipped contents to $DATAFILE"
+        rm -rf "$GAMEDIR/assets/"*
+		
+		sleep 1
 }
 
-install_complete() {
 # Create install completion flag
-touch "install_completed"
-echo "Installation completed successfully!"
-echo "-----------------------------"
-echo "Process finished at: $(date)"
+install_complete() {
+	touch "install_completed"
+    # Measure time to complete
+	END_TIME=$(date +%s)
+    DURATION=$((END_TIME - START_TIME))
+    echo "Script completed in $DURATION seconds"
+	echo "Installation completed successfully!"
+	echo "-----------------------------"
+	echo "Process finished at: $(date)"
 }
 
-process_game() {
-    # Delete unnecessary files
-    remove_files
-	sleep 1
-    apply_xdeltas
-    sleep 1
+process_game() { 
+    echo "Preparing game..."
+    prepare_files || patch_failure
+	echo "Patching data.win..."
+	apply_xdeltas || patch_failure
+    echo "Externalizing textures..."
+    dump_textures || patch_failure
     echo "Compressing audio..."
-    compress_audio
-    sleep 1
-    echo "Finishing up..."
-    zip_archive
-    sleep 1
+	compress_audio || patch_failure
+	echo "Finishing up..."
+    zip_archive || patch_failure
     install_complete
+	sleep 1
+	
+    # Unmount runtimes
+    $ESUDO umount "$DOTNETDIR"
+    $ESUDO umount "$TOOLKIT"
+	
+    # Final completion message
+    echo "Patching process complete!"
 }
 
 # Call the function
