- don't quit for failed xdelta patch

diff --git a/ports/thecaribbeansail/thecaribbeansail/tools/patchscript b/ports/thecaribbeansail/thecaribbeansail/tools/patchscript
--- a/ports/thecaribbeansail/thecaribbeansail/tools/patchscript
+++ b/ports/thecaribbeansail/thecaribbeansail/tools/patchscript
@@ -101,7 +101,7 @@ apply_xdelta() {
     else
       echo "Failed to apply patch"
       echo "$output"
-      exit 1
+      # exit 1 # just carry on if patch fails (might be the steam file)
     fi
   else
     echo "No data.win file found to patch!"
