- convert to aarch64 gmloader

diff --git a/ports/thecaribbeansail/thecaribbeansail/tools/patchscript b/ports/thecaribbeansail/thecaribbeansail/tools/patchscript
--- a/ports/thecaribbeansail/thecaribbeansail/tools/patchscript
+++ b/ports/thecaribbeansail/thecaribbeansail/tools/patchscript
@@ -1,62 +1,185 @@
 #!/bin/bash
 
-#
-#   The Carabbean Sail patch script
-#   Author: kotzebuedog
-#   Version: 1.0
-#
-
-XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
-
-if [ -d "/opt/system/Tools/PortMaster/" ]; then
-  controlfolder="/opt/system/Tools/PortMaster"
-elif [ -d "/opt/tools/PortMaster/" ]; then
-  controlfolder="/opt/tools/PortMaster"
-elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
-  controlfolder="$XDG_DATA_HOME/PortMaster"
-else
-  controlfolder="/roms/ports/PortMaster"
-fi
-
-source $controlfolder/control.txt
-
-# Set GAMEDIR to the current directory and set logfile
-export GAMEDIR="$PWD"
+# set gamedit to the current directory and set logfile
+GAMEDIR="$PWD"
 LOGFILE="$GAMEDIR/patchlog.txt"
+LOGERR="$GAMEDIR/patchlog_error.txt"
+START_TIME=$(date +%s)
 
-# Redirect output and error to the log file
+# redirect output and error to the log file
 exec > >(tee -a "$LOGFILE") 2>&1
 echo "GAMEDIR is set to: $GAMEDIR"
 
-# Export lib and binary path
-export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$GAMEDIR/tools/libs.${DEVICE_ARCH}"
-export PATH="$PATH:$GAMEDIR/tools:$controlfolder"
-
-# -------------------- BEGIN FUNCTIONS --------------------
-
-patch_file()
-{
-    echo "Patching data.win"
-
-    [[ -f "$GAMEDIR/gamedata/data.win" ]] \
-    && xdelta3 -vv -d -s "$GAMEDIR/gamedata/data.win" "$GAMEDIR/tools/patch.xdelta3" "$GAMEDIR/gamedata/game.droid" \
-    && rm "$GAMEDIR/gamedata/data.win" \
-    && rm -f $GAMEDIR/gamedata/*.{dll,exe,win}
+# patch failure function
+patch_failure() {
+  mv "$LOGFILE" "$LOGERR"
+  $ESUDO umount "$DOTNETDIR"
+  $ESUDO umount "$TOOLKIT"
+  echo "Patching process failed."
+  exit 1
 }
 
-compress_audio()
-{
-    echo "Compressing audio"
+# mount the gmtoolkit runtime
+TOOLKIT="$HOME/gmtoolkit"
+RUNTIME="$controlfolder/libs/gmtoolkit.squashfs"
+if [ -f "$RUNTIME" ]; then
+  $ESUDO mkdir -p "$TOOLKIT"
+  $ESUDO umount "$RUNTIME" || true
+  $ESUDO mount "$RUNTIME" "$TOOLKIT"
+else
+  echo "This port requires the GMToolkit runtime. Please download it."
+  sleep 2
+  patch_failure
+fi
 
-    gmKtool.py -vv -m 0 -b 64 "$GAMEDIR/gamedata/game.droid" -d tmp \
-    && mv "$GAMEDIR/tmp/game.droid" "$GAMEDIR/gamedata/game.droid" \
-    && rm -rf tmp
+# mount the dotnet runtime
+DOTNETDIR="$HOME/mono"
+DOTNETFILE="$controlfolder/libs/dotnet-8.0.12.squashfs"
+if [ -f "$DOTNETFILE" ]; then
+  $ESUDO mkdir -p "$DOTNETDIR"
+  $ESUDO umount "$DOTNETFILE" || true
+  $ESUDO mount "$DOTNETFILE" "$DOTNETDIR"
+else
+  echo "This port requires the Dotnet runtime. Please download it."
+  sleep 2
+  patch_failure
+fi
+
+# exports
+export PATH="$controlfolder:$DOTNETDIR:$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
+export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"
+export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
+export DATADIR="$GAMEDIR/assets"
+export DATAFILE="thecaribbeansail.port"
+export TMPDIR="$GAMEDIR/tmp"
+
+# permissions
+chmod 666 /dev/uinput
+
+# set up trap for cleaning tmpdir on exit
+trap 'rm -rf "$TMPDIR"; echo "Cleaned up temporary files." >> "$LOGFILE"' 0
+
+# attempt to get savedir from gmloader.json using jq
+if command -v jq >/dev/null 2>&1; then
+  SAVEDIR=$(jq -r '.save_dir // empty' "$GAMEDIR/gmloader.json" 2>/dev/null)
+else
+  SAVEDIR="$GAMEDIR/saves"
+fi
+
+# test for commands: python, zip
+PYTHON=$(which python3)
+if [ -z "$PYTHON" ]; then
+  echo "Missing Python!"
+  patch_failure
+fi
+
+ZIP=$(which zip)
+if [ -z "$ZIP" ]; then
+  echo "Missing zip!"
+  patch_failure
+fi
+
+prepare_files() {
+  mkdir -p "$SAVEDIR"
+
+  # delete excess files
+  find "$DATADIR" -type f \( \
+    -name "*.exe" -o -name "*.dll" -o -name "*.hashdb" -o \
+    -name "*.ico" -o -name "*.lnk" -o -name "*.msg" -o -name "*.zip" \
+  \) -exec rm -f {} \;
 }
 
-# --------------------- END FUNCTIONS ---------------------
+apply_xdelta() {
+  # check if the data.win file exists and apply xdelta
+  if [ -f "$DATADIR/data.win" ]; then
+    echo "Applying xdelta patch"
+    output=$(xdelta3 -d -s "$DATADIR/data.win" -f "./tools/itch_patch.xdelta3" "$DATADIR/game.droid" 2>&1)
+    if [ $? -eq 0 ]; then
+      echo "Patch applied successfully"
+      echo "$output"
+      rm "$DATADIR/data.win"
+    else
+      echo "Failed to apply patch"
+      echo "$output"
+      exit 1
+    fi
+  else
+    echo "No data.win file found to patch!"
+  fi
 
-patch_file && compress_audio
+  sleep 1
+}
 
-[[ ! $? -eq 0 ]] && echo "Patching process failed!" && exit 1
+compress_audio() {  
+  if $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"; then
+    mv "$TMPDIR/"* "$DATADIR" && rmdir "$TMPDIR"
+    echo "Audio compression applied successfully."
+  else
+    # failure
+    echo "Audio compression failed for game.droid."
+    rmdir "$TMPDIR"
+    patch_failure
+  fi
 
-echo "Patching process done!"
+  sleep 1
+
+  # find and compress all .ogg files in the /gamedata directory
+  find "$DATADIR" -type f -name "*.ogg" | while read -r file; do
+    # create a temporary file for the compressed version
+    temp_file="${file%.ogg}_temp.ogg"
+  
+    # fecode the .ogg file and encode it with the specified bitrate
+    if "$TOOLKIT/gmtools/oggdec" -o - "$file" 2>/dev/null | "$TOOLKIT/gmtools/oggenc" -b 64 -o "$temp_file" - 2>/dev/null; then
+      # replace the original file with the compressed version if successful
+      mv "$temp_file" "$file"
+      echo "Compressed: $file to 64 kbps"
+    else
+      echo "Failed to compress: $file" >&2
+      rm -f "$temp_file" # clean up the temp file in case of error
+    fi
+  done
+
+  echo "All .ogg files have been processed."
+  sleep 1
+}
+
+zip_archive() {
+  zip -r -0 "$DATAFILE" ./assets/
+  echo "Zipped contents to $DATAFILE"
+  rm -rf "$GAMEDIR/assets/"*
+
+  sleep 1
+}
+
+# create install completion flag
+install_complete() {
+  touch "install_completed"
+  # measure time to complete
+  END_TIME=$(date +%s)
+  DURATION=$((END_TIME - START_TIME))
+  echo "Script completed in $DURATION seconds"
+  echo "Installation completed successfully!"
+  echo "-----------------------------"
+  echo "Process finished at: $(date)"
+}
+
+process_game() { 
+  echo "Preparing game..."
+  prepare_files || patch_failure
+  echo "Patching data.win..."
+  apply_xdelta || patch_failure
+  echo "Compressing audio..."
+  compress_audio || patch_failure
+  echo "Finishing up..."
+  zip_archive || patch_failure
+  install_complete
+  sleep 1
+  # unmount runtimes
+  $ESUDO umount "$DOTNETDIR"
+  $ESUDO umount "$TOOLKIT"
+  # final completion message
+  echo "Patching process complete!"
+}
+
+# call
+process_game
