Revert dumping textures for UTYellow

diff --git a/ports/utyellow/utyellow/tools/patchscript b/ports/utyellow/utyellow/tools/patchscript
--- a/ports/utyellow/utyellow/tools/patchscript
+++ b/ports/utyellow/utyellow/tools/patchscript
@@ -10,7 +10,6 @@ echo "GAMEDIR is set to: $GAMEDIR"
 
 # Patch failure function
 patch_failure() {
-    $ESUDO umount "$DOTNETDIR" 2>/dev/null || true
     $ESUDO umount "$TOOLKIT" 2>/dev/null || true
     # Exit script, or return if sourced
     return 1 2>/dev/null || exit 1
@@ -29,21 +28,8 @@ else
     patch_failure
 fi
 
-# Mount the dotnet runtime
-DOTNETDIR="$HOME/mono"
-DOTNETFILE="$controlfolder/libs/dotnet-8.0.12.squashfs"
-if [ -f "$DOTNETFILE" ]; then
-    $ESUDO mkdir -p "$DOTNETDIR"
-    $ESUDO umount "$DOTNETDIR" 2>/dev/null || true
-    $ESUDO mount "$DOTNETFILE" "$DOTNETDIR"
-else
-    echo "This port requires the Dotnet runtime. Please download it."
-    sleep 2
-    patch_failure
-fi
-
 # Exports
-export PATH="$DOTNETDIR:$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
+export PATH="$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
 export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"
 export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
 export DATADIR="$GAMEDIR/assets"
@@ -93,50 +79,27 @@ prepare_files() {
     fi
 }
 
-# Externalize game textures with compression
-dump_textures() {
-    # Purge cache before operations
-    rm -rf "$TMPDIR/"*
-    
-    # Export sprites we don't want to compress
-    export UMT_SPRITES_FOLDER="$GAMEDIR/tmp/Sprites"
-    export UMT_PADDED="true"
-    export UMT_SPRITE_NAMES="spr_final_palette"
-    export UMT_SPRITE_PREFIX="spr_pl_"
-    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
-        load "$DATADIR/data.win" \
-        -s "$GAMEDIR/tools/ExportSprites.csx"      
-    
-    if [ $? -ne 0 ]; then
-        echo "[DOTNET]: Failed to export sprites"
-        patch_failure
-    fi
-    
-    # Begin astc texture compression
-    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
-        dump "$DATADIR/data.win" \
-        -e "$DATADIR/textures" "$DATADIR/game.droid"
-
-    if [ $? -ne 0 ]; then
-        echo "[DOTNET]: Texture dumping failed to apply."
-        patch_failure
-    else
-        rm -f "$DATADIR/data.win"
-        rm -rf "$SAVEDIR/textures" # Remove previous texture directory if it exists
-        mv "$DATADIR/textures" "$SAVEDIR/textures"
-    fi
-    
-    # Import the sprites we preserved
-    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
-        load "$DATADIR/game.droid" \
-        -s "$GAMEDIR/tools/ImportSprites.csx" \
-        -o "$DATADIR/game.droid"
-    
-    if [ $? -ne 0 ]; then
-        echo "[DOTNET]: Failed to reimport sprites"
-        patch_failure
-    else
-        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
+apply_xdelta() {
+    # Check if the data.win file exists and apply xdelta
+    if [ -f "$DATADIR/data.win" ]; then
+        if [ "$(md5sum "$DATADIR/data.win" | awk '{print $1}')" == "db15b9fb5662207e3d4b329d1c00bc70" ]; then
+            # English v1.1.0
+            output=$($controlfolder/xdelta3 -d -s "$DATADIR/data.win" -f "./tools/patches/utyellow-en.xdelta" "$DATADIR/game.droid" 2>&1)
+        elif [ "$(md5sum "$DATADIR/data.win" | awk '{print $1}')" == "328e499caf024644a9399b49afd4c8b7" ]; then
+            # Espanol
+            output=$($controlfolder/xdelta3 -d -s "$DATADIR/data.win" -f "./tools/patches/utyellow-es.xdelta" "$DATADIR/game.droid" 2>&1)
+        fi
+        
+        # Success / Failure
+        if [ $? -eq 0 ]; then
+            echo "Patch applied successfully"
+            echo "$output"
+            rm "$DATADIR/data.win"
+        else
+            echo "Failed to apply patch"
+            echo "$output"
+            patch_failure
+        fi
     fi
 }
 
@@ -161,8 +124,8 @@ zip_archive() {
 process_game() { 
     echo "Preparing game..."
     prepare_files || { patch_failure; return 1; }
-    echo "Externalizing textures..."
-    dump_textures || { patch_failure; return 1; }
+    echo "Applying xdelta patch..."
+    apply_xdelta || { patch_failure; return 1; }
     echo "Compressing audio..."
     compress_audio || { patch_failure; return 1; }
     sleep 1
@@ -179,5 +142,4 @@ else
 fi
 
 # Unmount runtimes
-$ESUDO umount "$DOTNETDIR" 2>/dev/null || true
 $ESUDO umount "$TOOLKIT" 2>/dev/null || true
