- re-add xdelta

diff --git a/ports/qyoblaster/qyoblaster/tools/patchscript b/ports/qyoblaster/qyoblaster/tools/patchscript
--- a/ports/qyoblaster/qyoblaster/tools/patchscript
+++ b/ports/qyoblaster/qyoblaster/tools/patchscript
@@ -1,16 +1,5 @@
 #!/bin/bash
 
-XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
-if [ -d "/opt/system/Tools/PortMaster/" ]; then
-  controlfolder="/opt/system/Tools/PortMaster"
-elif [ -d "/opt/tools/PortMaster/" ]; then
-  controlfolder="/opt/tools/PortMaster"
-elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
-  controlfolder="$XDG_DATA_HOME/PortMaster"
-else
-  controlfolder="/roms/ports/PortMaster"
-fi
-
 # Set GAMEDIR to the current directory and set logfile
 GAMEDIR="$PWD"
 LOGFILE="$GAMEDIR/patchlog.txt"
@@ -47,10 +36,19 @@ unzip_audiogroups() {
 }
 
 apply_patch() {
-    # Pre-Patch data.win
-    if [ -f "./gamedata/data.win" ]; then
-        $controlfolder/xdelta3 -d -s "$DATADIR/data.win" "./tools/patches/patch.xdelta3" "$DATADIR/game.droid"
-        [ $? -eq 0 ] && rm "$DATADIR/data.win" || echo "Patching of data.win has failed"
+    # Patch data.win
+    if [ -f "$DATADIR/data.win" ]; then
+        echo "Applying xdelta patch"
+        output=$(xdelta3 -d -s "$DATADIR/data.win" "./tools/patches/patch.xdelta3" "$DATADIR/game.droid" 2>&1)
+        if [ $? -eq 0 ]; then
+            echo "Patch applied successfully"
+            echo "$output"
+            rm "$DATADIR/data.win"
+        else
+            echo "Failed to apply patch"
+            echo "$output"
+            exit 1
+        fi
     fi
 }
 
