Split patchscript (patching vs updating)

diff --git a/ports/riskofrain/riskofrain/tools/patchscript b/ports/riskofrain/riskofrain/tools/patchscript
--- a/ports/riskofrain/riskofrain/tools/patchscript
+++ b/ports/riskofrain/riskofrain/tools/patchscript
@@ -37,39 +37,6 @@ DATA_WIN_MD5="d32c0d93bfc23b242fe7fca90f1d07ef"
 
 # -------------------- BEGIN FUNCTIONS --------------------
 
-update_install_671b20f()
-{
-    # Update from previous install (git commit 671b20f)
-    files_to_move=(
-        "Prefs.ini"
-        "Save.ini"
-        "game.droid"
-        "options.ini"
-    )
-
-    for file in "${files_to_move[@]}"; do
-        echo "Moving $file"
-        mv "$file" "$GAMEDIR/gamedata/"
-        [[ ! $? -eq 0 ]] && echo "Cannot move $file" && return 1 # CRITICAL
-    done
-
-    echo "Renaming game.apk"
-    mv "$GAMEDIR/game.apk" "$GAMEDIR/riskofrain.port"
-    [[ ! $? -eq 0 ]] && echo "Cannot rename game.apk" && return 1 # CRITICAL
-
-    files_to_delete=(
-        "gmloadernext"
-    )
-
-    for file in "${files_to_delete[@]}"; do
-        echo "Deleting $file"
-        rm "$file"
-    done
-
-    return 0
-
-}
-
 cleanup_files()
 {
     # Delete unnecessary files
@@ -151,17 +118,9 @@ patch_game()
 
 # --------------------- END FUNCTIONS ---------------------
 
-# If previous installation (671b20f) is detected update and exit
-# (no need to install the game again)
-if [[ -f "$GAMEDIR/game.apk" ]]; then
-    update_install_671b20f
-    [[ ! $? -eq 0 ]] && echo "Cannot update game" \
-    && echo "Patching process failed!" && exit 1 \
-    || echo "Game updated" && echo "Patching process done!" && exit 0
-fi
-
 # Install the game
 patch_game && install_conf && pack_assets && cleanup_files
 [[ ! $? -eq 0 ]] && echo "Cannot install the game" \
-&& echo "Patching process failed!" && exit 1 \
-|| echo "Patching process done!" && exit 0
+&& echo "Patching process failed!" && exit 1
+
+echo "Patching process done!" && exit 0
